spring:
  profiles:
    active: ${PROFILE}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true

---
spring:
  datasource:
    driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: local
mail:
  server:
    url: http://localhost:8080

---
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      username: ${USERNAME}
      password: ${PASSWORD}
  config:
    activate:
      on-profile: prod

mail:
  server:
    url: ${MAIL_SERVER_URL}
